blog/urls.py
from django.urls import path

from .views import index
from .views import author_page
from .views import article_page
from .views import test_page
from .views import Create_Article

urlpatterns = [
    path('author/<id>',author_page),
    path('article/<id>',article_page),
    path('',index,name='main_page'),
    path('tmp/',test_page),
    path('create/',Create_Article.as_view()),
]

main_project/urls.py
from django.contrib import admin
from django.urls import path,include

from connection.views import get_message
from connection.views import thanks
from django_registration.backends.activation.views import RegistrationView
from blog.forms import AuthorForm

urlpatterns = [
    path('',include('blog.urls')),
    #path('accounts/',include('enter_user.urls')),
    path('accounts/register/',
        RegistrationView.as_view(
            form_class=AuthorForm
        ),
        name='django_registration_register',
    ),
    path('admin/', admin.site.urls),
    path('get_message/',get_message,name='get_message'),
    path('thanks/',thanks,name='thanks'),
    path('auth/', include('django.contrib.auth.urls')),

]

blog/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)


class AuthorManager(BaseUserManager):
    def create_user(self, email,age, password=None):
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            age=age,
        )

        user.set_password(password)
        print(user.password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email,age, password=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            password=password,
            age=age,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user



class Author(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    age = models.IntegerField()
    
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = AuthorManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['age']

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        print('IS ADMIN',self.is_admin)
        return self.is_admin





'''
class Author(AbstractUser):
    age = models.IntegerField()
    
'''


class Article(models.Model):
    title = models.CharField(max_length=51)
    text = models.TextField()
    image = models.ImageField(upload_to='static/')
    publication = models.DateField()
    author = models.ManyToManyField(Author)

templates/123.html
<h1>1234567</h1>

templates/article.html
{% extends 'layout5.html' %}
{% load static %}


{% block menu %}
	{% include 'menu.html '%}
{% endblock %}

{% block content %}
					<div id="main">
						<div class="inner">
							<h1>{{article.title}}</h1>
							<span class="image main"><img src="/{{article.image}}" alt="" /></span>
							<p>{{article.text}}</p>
							<h4>Автори статті</h4>

							{% for author in article.author.all %}
								<a href="/author/{{author.id}}">{{author}}</a>
							{% endfor %}
						</div>
					</div>
{% endblock %}



{% block socials %}
		{% include 'social.html' %}
{% endblock  %}

templates/author.html
{% extends 'layout5.html' %}
{% load static %}


{% block menu %}
{% include 'menu.html '%}
{% endblock %}


{% block content %}
					<div id="main">
						<div class="inner">
							<h1>{{author.name}}</h1>
							<span class="image main"><img src="/{{author.image}}" alt="" /></span>
							<p>{{article.age}}</p>
							<h4> Статті цього автора </h4>
							{% for article in author.article_set.all %}
								<a href="/article/{{article.id}}">{{article.title}}</a>
							{% endfor %}
						</div>
					</div>
{% endblock %}

{% block socials %}
		{% include 'social.html' %}
{% endblock  %}

templates/index.html
{% extends 'layout5.html' %}
{% load static %}


{% block menu %}
{% include 'menu.html' %}
{% endblock %}





{% block content %}
				<!-- Main -->
					<div id="main">
						<div class="inner">
							<header>
								<h1>Сайт блогу</h1>
								<p>Опис блогу</p>
							</header>
							<section class="tiles">





								{% for article in articles %}
								<article class="style1">
									<span class="image">
										<img src="{{article.image}}" alt="" />
									</span>
									<a href="/article/{{article.id}}">
										<h2>{{article.title}}</h2>
										<div class="content">
											<p>{{article.text}}</p>
										</div>
									</a>
								</article>
								{% endfor %}






							</section>
						</div>
					</div>
{% endblock %}


{% block socials %}
	{% include 'social.html' %}
{% endblock  %}

templates/layout.html
{% load static %}
<!DOCTYPE HTML>
<!--
	Phantom by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>Phantom by HTML5 UP</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
		<noscript><link rel="stylesheet" href="{% static 'assets/css/noscript.css' %}" /></noscript>
	</head>
	<body class="is-preload">
		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Header -->
					<header id="header">
						<div class="inner">

							<!-- Logo -->
								<a href="/" class="logo">
									<span class="symbol"><img src="images/logo.svg" alt="" /></span><span class="title">Phantom</span>
								</a>

							<!-- Nav -->
								<nav>
									<ul>
										<li><a href="#menu">Menu</a></li>
									</ul>
								</nav>

						</div>
					</header>

				<!-- Menu -->
					<nav id="menu">
						<h2>Menu</h2>
						<ul>
							<li><a href="index.html">Home</a></li>
							<li><a href="generic.html">Ipsum veroeros</a></li>
							<li><a href="generic.html">Tempus etiam</a></li>
							<li><a href="generic.html">Consequat dolor</a></li>
							<li><a href="elements.html">Elements</a></li>
						</ul>
					</nav>




					{% block content %}
					{% endblock %}






				<!-- Footer -->
					<footer id="footer">
						<div class="inner">
							<section>
								<h2>Get in touch</h2>
								<form method="post" action="#">
									<div class="fields">
										<div class="field half">
											<input type="text" name="name" id="name" placeholder="Name" />
										</div>
										<div class="field half">
											<input type="email" name="email" id="email" placeholder="Email" />
										</div>
										<div class="field">
											<textarea name="message" id="message" placeholder="Message"></textarea>
										</div>
									</div>
									<ul class="actions">
										<li><input type="submit" value="Send" class="primary" /></li>
									</ul>
								</form>
							</section>
							<section>
								<h2>Follow</h2>
								<ul class="icons">
									<li><a href="#" class="icon brands style2 fa-twitter"><span class="label">Twitter</span></a></li>
									<li><a href="#" class="icon brands style2 fa-facebook-f"><span class="label">Facebook</span></a></li>
									<li><a href="#" class="icon brands style2 fa-instagram"><span class="label">Instagram</span></a></li>
									<li><a href="#" class="icon brands style2 fa-dribbble"><span class="label">Dribbble</span></a></li>
									<li><a href="#" class="icon brands style2 fa-github"><span class="label">GitHub</span></a></li>
									<li><a href="#" class="icon brands style2 fa-500px"><span class="label">500px</span></a></li>
									<li><a href="#" class="icon solid style2 fa-phone"><span class="label">Phone</span></a></li>
									<li><a href="#" class="icon solid style2 fa-envelope"><span class="label">Email</span></a></li>
								</ul>
							</section>
							<ul class="copyright">
								<li>&copy; Untitled. All rights reserved</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
							</ul>
						</div>
					</footer>

			</div>

		<!-- Scripts -->
			<script src="{% static 'assets/js/jquery.min.js' %}"></script>
			<script src="{% static 'assets/js/browser.min.js' %}"></script>
			<script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
			<script src="{% static 'assets/js/util.js' %}"></script>
			<script src="{% static 'assets/js/main.js' %}"></script>

	</body>
</html>

templates/layout2.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8">
	<title>{% block title%}{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" >
</head>

<body>





{% block content %}
{% endblock %}






<script type="text/javascript" src="{% static 'script.js' %} "></script>
</body>
</html>

templates/layout5.html
{% load static %}
<!DOCTYPE HTML>
<!--
	Phantom by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>Phantom by HTML5 UP</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'blog/assets/css/main.css' %}" />
		<noscript><link rel="stylesheet" href="{% static 'blog/assets/css/noscript.css' %}" /></noscript>
	</head>
	<body class="is-preload">
		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Header -->
					<header id="header">
						<div class="inner">

							<!-- Logo -->
								<a href="/" class="logo">
									<span class="symbol"><img src="{% static 'blog/images/logo.svg'%}" alt="" /></span><span class="title">Phantom</span>
								</a>

							<!-- Nav -->
								<nav>
									<ul>
										<li><a href="#menu">Menu</a></li>
									</ul>
								</nav>

						</div>
					</header>

				<!-- Menu -->
					<nav id="menu">
						<h2>Меню</h2>
						<ul>
							{% block menu %}
							{% endblock %}					
						</ul>
					</nav>

					{% block content %}
					{% endblock %}

				<!-- Footer -->
					<footer id="footer">
						<div class="inner">
							<section>
								<h2>Зв'язатись з нами</h2>

								<form method="post" action="{% url 'get_message' %}">
									{% csrf_token %}
									<div class="fields">
										<div class="field half">
											<input type="text" name="name" id="name" placeholder="Ім'я" />
										</div>
										<div class="field half">
											<input type="email" name="email" id="email" placeholder="Email" />
										</div>
										<div class="field">
											<textarea name="message" id="message" placeholder="Повідомлення"></textarea>
										</div>
									</div>
									<ul class="actions">
										<li><input type="submit" value="Надіслати" class="primary" /></li>
									</ul>
								</form>

							</section>
							<section>
								<h2>Слідкувати</h2>
								<ul class="icons">
									{% block socials %}
									{% endblock %}
								</ul>
							</section>
							<ul class="copyright">
								<li>&copy; Untitled. All rights reserved</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
							</ul>
						</div>
					</footer>

			</div>

		<!-- Scripts -->
			<script src="{% static 'blog/assets/js/jquery.min.js' %}"></script>
			<script src="{% static 'blog/assets/js/browser.min.js' %}"></script>
			<script src="{% static 'blog/assets/js/breakpoints.min.js' %}"></script>
			<script src="{% static 'blog/assets/js/util.js' %}"></script>
			<script src="{% static 'blog/assets/js/main.js' %}"></script>

	</body>
</html>

templates/social.html
{% for social in request.social %}
		<li><a href="{{social.link}}" class="icon brands style2 {{social.icon}}"><span class="label">{{social.name}}</span></a></li>
{% endfor%}

templates/sorry.html
{% extends 'layout5.html' %}

{% block menu %}
{% include 'menu.html' %}
{% endblock %}



{% block content %}
	<h1 align="center">ВИБАЧТЕ НАЖАЛЬ СТАТЕЙ НЕМАЄ !!</h1>


{% endblock %}


{% block socials %}

		{% for social in socials %}
			<li><a href="{{social.link}}" class="icon brands style2 {{social.icon}}"><span class="label">{{social.name}}</span></a></li>
		{% endfor%}

{% endblock %}

templates/thank.html
{% extends 'layout5.html' %}


{% block content %}
	<h1 align="center">ДЯКУЄМО ЗА ЗВЕРНЕННЯ !!</h1>


{% endblock %}


{% block socials %}

		{% for social in socials %}
			<li><a href="{{social.link}}" class="icon brands style2 {{social.icon}}"><span class="label">{{social.name}}</span></a></li>
		{% endfor%}

{% endblock %}

templates/thanks.html
{% extends 'layout5.html' %}


{% block menu %}
{% include 'menu.html '%}
{% endblock %}


{% block content %}
	<h1 align="center">ДЯКУЄМО ЗА ЗВЕРНЕННЯ !!</h1>

	{% include '123.html' %}
{% endblock %}


{% block socials %}
		{% include 'social.html' %}
{% endblock %}

templates/tmp.html
{% extends 'lay4.html' %}
{% load static %}

{% block title %}
ТЕСТОВА СТОРІНКА
{% endblock %}


{% block content %}



				<!-- One -->
					<section class="banner style1 orient-left content-align-left image-position-right fullscreen onload-image-fade-in onload-content-fade-right">
						<div class="content">
							<h1>Story</h1>
							<p class="major">A (modular, highly tweakable) responsive one-page template designed by <a href="https://html5up.net">HTML5 UP</a> and released for free under the <a href="https://html5up.net/license">Creative Commons</a>.</p>
							<ul class="actions stacked">
								<li><a href="#first" class="button big wide smooth-scroll-middle">Get Started</a></li>
							</ul>
						</div>
						<div class="image">
							<img src="{% static 'tmp2/images/banner.jpg' %}" alt="" />
						</div>
					</section>





{% endblock %}

templates/tmp2.html
{% extends 'layout2.html' %}


{% block title %}
СТОРІНКА 2
{% endblock %}

{% block content %}



{% if articles|length > 0 %}

{% else %}
ЗАПИСІВ НЕМАЄ

{% endif %}


<div class="block1">
	<h2>HHHHHHH</h2>
	<p>WWWWWWW</p>
</div>

<div class="block1">
	<h2>HHHHHHH</h2>
	<p>WWWWWWW</p>
</div>

<div class="block1">
	<h2>HHHHHHH</h2>
	<p>WWWWWWW</p>
</div>

<div class="block1">
	<h2>HHHHHHH</h2>
	<p>WWWWWWW</p>
</div>

<div class="block1">
	<h2>HHHHHHH</h2>
	<p>WWWWWWW</p>
</div>


{% endblock %}